### ISSUE TITLE
Regression on updating glium to 0.21

### ISSUE THREAD

**Issue by malikolivier** [Gekkio/imgui-rs#115]
I get a panic when I run an example, to be specific the program panics when I close the window.
Here is the backtrace:

```
imgui-rs/imgui-examples$  cargo run --example test_window_impl
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling imgui-sys v0.0.19-pre (file:///home/malik/workspace/lab/aflak-backend/node_editor/imgui-rs/imgui-sys)
warning: third-party/cimgui/imgui/imgui.cpp: In function ‘void ImGui::RenderTriangle(ImVec2, ImGuiDir, float)’:
warning: third-party/cimgui/imgui/imgui.cpp:3136:11: warning: this statement may fall through [-Wimplicit-fallthrough=]
warning:          r = -r; // ...fall through, no break!
warning:          ~~^~~~
warning: third-party/cimgui/imgui/imgui.cpp:3137:5: note: here
warning:      case ImGuiDir_Down:
warning:      ^~~~
warning: third-party/cimgui/imgui/imgui.cpp:3144:11: warning: this statement may fall through [-Wimplicit-fallthrough=]
warning:          r = -r; // ...fall through, no break!
warning:          ~~^~~~
warning: third-party/cimgui/imgui/imgui.cpp:3145:5: note: here
warning:      case ImGuiDir_Right:
warning:      ^~~~
   Compiling imgui v0.0.19-pre (file:///home/malik/workspace/lab/aflak-backend/node_editor/imgui-rs)
   Compiling imgui-glium-renderer v0.0.19-pre (file:///home/malik/workspace/lab/aflak-backend/node_editor/imgui-rs/imgui-glium-renderer)
   Compiling imgui-gfx-renderer v0.0.19-pre (file:///home/malik/workspace/lab/aflak-backend/node_editor/imgui-rs/imgui-gfx-renderer)
   Compiling imgui-examples v0.0.19-pre (file:///home/malik/workspace/lab/aflak-backend/node_editor/imgui-rs/imgui-examples)
    Finished dev [unoptimized + debuginfo] target(s) in 7.97 secs
     Running `/home/malik/workspace/lab/aflak-backend/node_editor/imgui-rs/target/debug/examples/test_window_impl`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Failed to close input method: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 14, minor_code: 0 }', libcore/result.rs:945:5
stack backtrace:
   0:     0x560e950f373b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h04b64c0b7eb0f971
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x560e950f88b0 - std::sys_common::backtrace::print::hb360173233c238e6
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x560e950efcdd - std::panicking::default_hook::{{closure}}::h0e90b589ae160518
                               at libstd/panicking.rs:206
   3:     0x560e950efa3b - std::panicking::default_hook::h9e2e7a84308b857d
                               at libstd/panicking.rs:222
   4:     0x560e950f012f - std::panicking::rust_panic_with_hook::h4c26a26719bbb9f2
                               at libstd/panicking.rs:400
   5:     0x560e950eff52 - std::panicking::begin_panic_fmt::h0a3da897d88b61f1
                               at libstd/panicking.rs:347
   6:     0x560e950efe82 - rust_begin_unwind
                               at libstd/panicking.rs:323
   7:     0x560e95138e50 - core::panicking::panic_fmt::h3ce52437f219108e
                               at libcore/panicking.rs:71
   8:     0x560e95010f47 - core::result::unwrap_failed::h9e1af3aed6493b0b
                               at /checkout/src/libcore/macros.rs:26
   9:     0x560e9500e73b - <core::result::Result<T, E>>::expect::h0d7e65e9f4769f1c
                               at /checkout/src/libcore/result.rs:809
  10:     0x560e94f9fcdc - <winit::platform::platform::x11::util::Ime as core::ops::drop::Drop>::drop::h9fa8f93fdb682b6d
                               at /home/malik/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.12.0/src/platform/linux/x11/util.rs:409
  11:     0x560e94fceeb4 - core::ptr::drop_in_place::h5dedec27e3738995
                               at /checkout/src/libcore/ptr.rs:59
  12:     0x560e94fcf258 - core::ptr::drop_in_place::h646526bc20da7aae
                               at /checkout/src/libcore/ptr.rs:59
  13:     0x560e94f969ff - <std::collections::hash::table::RawTable<K, V>>::rev_drop_buckets::hae691bb1650b9b9d
                               at /checkout/src/libstd/collections/hash/table.rs:894
  14:     0x560e94f9db0c - <std::collections::hash::table::RawTable<K, V> as core::ops::drop::Drop>::drop::hae127ff126c35ff8
                               at /checkout/src/libstd/collections/hash/table.rs:1177
  15:     0x560e94d6c264 - core::ptr::drop_in_place::h02de574b430ae9aa
                               at /checkout/src/libcore/ptr.rs:59
  16:     0x560e94d6eca8 - core::ptr::drop_in_place::had031417ba323aae
                               at /checkout/src/libcore/ptr.rs:59
  17:     0x560e94d704e4 - core::ptr::drop_in_place::hfa6b739091dffcd0
                               at /checkout/src/libcore/ptr.rs:59
  18:     0x560e94d6f768 - core::ptr::drop_in_place::hcb683fb7fdc0869f
                               at /checkout/src/libcore/ptr.rs:59
  19:     0x560e94d6cc55 - core::ptr::drop_in_place::h2ccbf2e4931ee9dd
                               at /checkout/src/libcore/ptr.rs:59
  20:     0x560e94d6f2b1 - core::ptr::drop_in_place::hb47beb4392356941
                               at /checkout/src/libcore/ptr.rs:59
  21:     0x560e94d6e014 - core::ptr::drop_in_place::h6819a226cc6db7f2
                               at /checkout/src/libcore/ptr.rs:59
  22:     0x560e94d992ff - test_window_impl::support::run::h1bbf30439ef0989b
                               at imgui-examples/examples/support/mod.rs:154
  23:     0x560e94da9563 - test_window_impl::main::h0913cc4c2c0c3a9d
                               at imgui-examples/examples/test_window_impl.rs:163
  24:     0x560e94d991b1 - std::rt::lang_start::{{closure}}::h6c74a0ceb423d3d1
                               at /checkout/src/libstd/rt.rs:74
  25:     0x560e950efde7 - std::panicking::try::do_call::hd5cf7f440bfa8115
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:305
  26:     0x560e950ffa3e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:101
  27:     0x560e950e8bb5 - std::rt::lang_start_internal::h9444fe72b19be1f8
                               at libstd/panicking.rs:284
                               at libstd/panic.rs:361
                               at libstd/rt.rs:58
  28:     0x560e94d99191 - std::rt::lang_start::h9c650f9e809fbbb3
                               at /checkout/src/libstd/rt.rs:74
  29:     0x560e94daaf6d - main
  30:     0x7f95645181c0 - __libc_start_main
  31:     0x560e94d57039 - _start
  32:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

After a `git bisect`, I found that the incriminating commit was f815daefd3a6f4e9b27f6825c56dad69b0fdc024.

Reverting this commit solves the issue.

I am running Ubuntu 17.10 with X11 and i3 as a windows manager. I wonder if this is a regression in Glium 0.21.

**EDIT:** I could reproduce with Gnome and X11. However the bug is not reproducible when using Gnome and Wayland.

**Comment by Gekkio** [comment]
This bug is unfortunately still open in `winit`: https://github.com/tomaka/winit/issues/480

**Comment by malikolivier** [comment]
Thanks! Fortunately, the patch that fixes that issue may land in the next `winit` release: https://github.com/tomaka/winit/pull/476

It'll then probably be fixed on the next `glium` release as well.

**Comment by parasyte** [comment]
I hit the same problem, and implemented the workaround described in https://github.com/tomaka/winit/issues/480 ... immediately exit the event loop on demand.

**Comment by Gekkio** [comment]
This regression is finally gone after updating `glium` :tada:
