### ISSUE TITLE
cargo run --example hello_gfx give stderr

### ISSUE THREAD

**Issue by whdxwym** [Gekkio/imgui-rs#206]
failed to run custom build command for `imgui-sys v0.0.23-pre (E:\rustprojects\imgui-rs\imgui-sys)`
process didn't exit successfully: `E:\rustprojects\imgui-rs\imgui-examples\target\debug\build\imgui-sys-bc8d451618b53f92\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/W4" "/Fo E:\\rustprojects\\imgui-rs\\imgui-examples\\target\\debug\\build\\imgui-sys-0535d0c8dbe49a18\\out\\third-party/cimgui\\cimgui.o" "/c" "third-party/cimgui/cimgui.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).

', C:\Users\lrmwy\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.28\src\lib.rs:2314:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by Gekkio** [comment]
Could you run it with `RUST_BACKTRACE=1` environment variable, so we can see some more details?

**Comment by joseluis** [comment]
Hi, I have exactly the same error, in a new installation of Linux Mint 19.1

```
$ RUST_BACKTRACE=1 cargo run --example hello_gfx
   Compiling imgui-sys v0.0.23-pre (/home/joseluis/dev-rust/_other/imgui-rs/imgui-sys)
   Compiling libloading v0.5.0
   Compiling quote v0.6.10
   Compiling rand_chacha v0.1.0
error: failed to run custom build command for `imgui-sys v0.0.23-pre (/home/joseluis/dev-rust/_other/imgui-rs/imgui-sys)`
process didn't exit successfully: `/home/joseluis/dev-rust/_other/imgui-rs/imgui-examples/target/debug/build/imgui-sys-45b93e8cb121d211/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("true")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/home/joseluis/dev-rust/_other/imgui-rs/imgui-examples/target/debug/build/imgui-sys-e87d8bb9124acb03/out/third-party/cimgui/cimgui.o" "-c" "third-party/cimgui/cimgui.cpp"
cargo:warning=c++: error: third-party/cimgui/cimgui.cpp: No existe el archivo o el directorio
cargo:warning=c++: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/home/joseluis/dev-rust/_other/imgui-rs/imgui-examples/target/debug/build/imgui-sys-e87d8bb9124acb03/out/third-party/cimgui/cimgui.o" "-c" "third-party/cimgui/cimgui.cpp" with args "c++" did not execute successfully (status code exit code: 1).

', /home/joseluis/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.28/src/lib.rs:2314:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: cc::fail
             at /home/joseluis/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.28/src/lib.rs:2314
   8: cc::Build::compile
             at /home/joseluis/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.28/src/lib.rs:951
   9: build_script_build::main
             at ./build.rs:2
  10: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Gekkio** [comment]
Ok, that backtrace tells us that you forgot to fetch the git submodules:

Run

```
git submodule update --init --recursive
```

**Comment by whdxwym** [comment]
it works for me, too. thank you.
