### ISSUE TITLE
Compiling in this repository? (v0.0.15)

### ISSUE THREAD

**Issue by Ploppz** [Gekkio/imgui-rs#73]
I tried to compile in the root directory.

```
((HEAD detached at v0.0.15)) $ cargo build
   Compiling bitflags v0.9.1
   Compiling gcc v0.3.53
   Compiling imgui-sys v0.0.15 (file:///home/ploppz/work/rust/CRATES/imgui-rs/imgui-sys)
warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
 --> imgui-sys/build.rs:4:5
  |
4 |     gcc::Config::new()
  |     ^^^^^^^^^^^^^^^^
  |
  = note: #[warn(deprecated)] on by default

error: failed to run custom build command for `imgui-sys v0.0.15 (file:///home/ploppz/work/rust/CRATES/imgui-rs/imgui-sys)`
process didn't exit successfully: `/home/ploppz/work/rust/CRATES/imgui-rs/target/debug/build/imgui-sys-67fb8ce33b91128a/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("true")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/home/ploppz/work/rust/CRATES/imgui-rs/target/debug/build/imgui-sys-1908936d5c7fe71d/out/third-party/cimgui/cimgui/cimgui.o" "-c" "third-party/cimgui/cimgui/cimgui.cpp"
cargo:warning=c++: error: third-party/cimgui/cimgui/cimgui.cpp: No such file or directory
cargo:warning=c++: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/home/ploppz/work/rust/CRATES/imgui-rs/target/debug/build/imgui-sys-1908936d5c7fe71d/out/third-party/cimgui/cimgui/cimgui.o" "-c" "third-party/cimgui/cimgui/cimgui.cpp" with args "c++" did not execute successfully (status code exit code: 1).

', /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.53/src/lib.rs:1659:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: gcc::fail
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.53/src/lib.rs:1659
   8: gcc::Build::compile
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.53/src/lib.rs:776
   9: build_script_build::main
             at imgui-sys/build.rs:4
  10: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  11: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  12: main
  13: __libc_start_main
  14: _start

```

I wanted to build it just to see the rustdocs of

**Comment by Gekkio** [comment]
You're missing the git submodules which contain the upstream libraries. Try running

```git submodule update --init --recursive```

**Comment by Ploppz** [comment]
Yes indeed, thanks.
